version: '2'
services:
  eurekaserver:
     image:   adminhubo/cloud-eureka-service:chapter3
     ports:
         - "8761:8761"
  configserver:
      image: adminhubo/cloud-confsvr-localfile:chapter2
      ports:
         - "8888:8888"
      environment:
         EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
         EUREKASERVER_PORT: "8761"
         ENCRYPT_KEY:       "IMSYMMENTRIC"
  database:
      image: postgres:9.5
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=eagle_eye_local
  licensingservice:
      image: adminhubo/cloud-licensing-service:chapter4
      ports:
        - "8080:8080"
        - "8090:8090"
      environment:
        PROFILE: "default"
        SERVER_PORT: "8080"
        CONFIGSERVER_URI: "http://configserver:8888"
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
        CONFIGSERVER_PORT:   "8888"
        DATABASESERVER_PORT: "5432"
        EUREKASERVER_PORT:   "8761"
        ENCRYPT_KEY:       "IMSYMMENTRIC"
  organizationservice:
      image: adminhubo/cloud-organization-service:chapter4
      ports:
        - "8085:8085"
      environment:
        PROFILE: "default"
        SERVER_PORT: "8085"
        CONFIGSERVER_URI: "http://configserver:8888"
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
        CONFIGSERVER_PORT:   "8888"
        DATABASESERVER_PORT: "5432"
        EUREKASERVER_PORT:   "8761"
        ENCRYPT_KEY:       "IMSYMMENTRIC"
