version: '2'
services:
  eurekaserver:
    image:   adminhubo/cloud-eureka-service:chapter3
    ports:
      - "8761:8761"
  configserver:
    image: adminhubo/cloud-confsvr-localfile:chapter2
    ports:
      - "8888:8888"
    environment:
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      ENCRYPT_KEY:       "IMSYMMENTRIC"
  # configserver2:
  #     image: adminhubo/cloud-confsvr-git:chapter2
  #     ports:
  #        - "8889:8889"
  #     links:
  #         - "eurekaserver:eurekaserver"
  #     environment:
  #       EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
  #       EUREKASERVER_PORT:8761
  #       ENCRYPT_KEY:       "IMSYMMENTRIC"
  database:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=eagle_eye_local
  licensingservice:
    image: adminhubo/cloud-licensing-service:chapter3
    ports:
      - "8081:8081"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8081"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_PORT:   "8888"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY:       "IMSYMMENTRIC"
  organizationservice:
    image: adminhubo/cloud-organization-service:chapter3
    ports:
      - "8082:8082"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8082"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_PORT:   "8888"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY:       "IMSYMMENTRIC"
  organizationservice2:
    image: adminhubo/cloud-organization-service:chapter3
    ports:
      - "8083:8083"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8083"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_PORT:   "8888"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY:       "IMSYMMENTRIC"
