version: '2'
services:
  eurekaserver:
   image:   adminhubo/cloud-eureka-service:chapter8
   ports:
       - "8761:8761"
  configserver:
    image: adminhubo/cloud-confsvr-localfile:chapter8
    ports:
       - "8888:8888"
    environment:
       EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
       EUREKASERVER_PORT: "8761"
       ENCRYPT_KEY:       "IMSYMMENTRIC"
  authenticationservice:
    image: adminhubo/cloud-authentication-service:chapter8
    ports:
      - "8901:8901"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8901"
      DATABASE_PORT:     5432
      CONFIGSERVER_PORT: 8888
      EUREKASERVER_PORT: 8761
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      ENCRYPT_KEY:       "IMSYMMENTRIC"
  zuulserver:
    image: adminhubo/cloud-zuul-service:chapter8
    ports:
      - "5555:5555"
    environment:
      PROFILE: "default"
      SERVER_PORT: "5555"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      DATABASESERVER_PORT: "5432"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_PORT:   "8888"
  database:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=eagle_eye_local
  licensingservice:
    image: adminhubo/cloud-licensing-service:chapter8
    ports:
      - "8080:8080"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8080"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      KAFKASERVER_URI: "kafkaserver"
      ZKSERVER_URI: "kafkaserver"
      DATABASESERVER_PORT: "5432"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_PORT:   "8888"
      ZUULSERVER_PORT:     "5555"
      KAFKASERVER_PORT:    "2181"
      REDIS_PORT:          "6379"
      ENCRYPT_KEY:       "IMSYMMENTRIC"
  organizationservice:
    image: adminhubo/cloud-organization-service:chapter8
    ports:
      - "8085:8085"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8085"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      KAFKASERVER_URI: "kafkaserver"
      ZKSERVER_URI: "kafkaserver"
      DATABASESERVER_PORT: "5432"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_PORT:   "8888"
      ZUULSERVER_PORT:     "5555"
      KAFKASERVER_PORT:    "2181"
      ENCRYPT_KEY:       "IMSYMMENTRIC"
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  kafkaserver:
    image: spotify/kafka
    ports:
      - 2181:2181
      - 9092:9092

  logspout:
    image: gliderlabs/logspout
    command: syslog://logs3.papertrailapp.com:23879
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock